FROM php:7.2-fpm
LABEL maintainer "shudo"

RUN apt-get update \
  && apt-get install -y \
  zlib1g-dev \
  mariadb-client \
  build-essential \
  vim \ 
  git \
  zip \
  unzip \
  && docker-php-ext-install zip pdo_mysql


#Composer install
# RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
# RUN php -r "if (hash_file('sha384', 'composer-setup.php') === 'baf1608c33254d00611ac1705c1d9958c817a1a33bce370c0595974b342601bd80b92a3f46067da89e3b06bff421f182') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
# RUN php composer-setup.php
# RUN php -r "unlink('composer-setup.php');"
# RUN mv composer.phar /usr/local/bin/composer

COPY --from=composer:latest /usr/bin/composer /usr/local/bin/composer

ENV COMPOSER_ALLOW_SUPERUSER 1

ENV COMPOSER_HOME /composer

ENV PATH $PATH:/composer/vendor/bin

RUN composer global require "laravel/installer"

# RUN curl -SL https://deb.nodesource.com/setup_13.x | bash
# RUN apt-get install -y nodejs && \
#   npm install -g npm@latest && \
#   npm install -g @vue/cli

WORKDIR /var/www